# this is only for search engines, it does not appear in the home
# as long as the json variables name and description are provided
title: Ath
description: hyde to my jekyll
baseurl: ""
url: https://nadath.github.io

# this information is shown on the homepage, all fields are optional and
# can be declared either as a single string or as a string array/hash
json:
  name: Ath
  description:
    - Welcome to
    - This tiny web
    - Of mine
  cv: assets/cv.pdf
  address:
    - University of Jekyll
    - Department of Themes
    - 123 Main St, Anytown, USA
  contact:
    #office: Foobar Hall 1.23
    phone: +11 6565 6797
    email: nadzair.nadia@gmail.com
  #demo: https://hacked-jekyll.netlify.app
  #source: https://github.com/piazzai/hacked-jekyll
  profiles:
    #facebook: https://www.facebook.com
    twitter: https://twitter.com/athaelas
    #instagram: https://www.instagram.com
    linkedin: https://www.linkedin.com/nadianadzair
    #stackoverflow: https://stackoverflow.com
    github: https://github.com/nadath

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  sourcemap: never
